### ISSUE TITLE
[iOS] Code will no longer run on the actual device, only the simulator works - ctypes unsigned

### ISSUE THREAD

**Issue by kloknibor** [beeware/briefcase#2046]
### Describe the bug

With my applications i was having issues that the application ran fine within the IOS simulator but not longer ran on my phone, but it crashed immediately. (I was able to install apps just fine before).

Because of this I wanted to start fresh and see if the same thing happened with the tutorial code, which unfortunately it did. The stack trace is the following:

Unable to install Python NSLog handler

### Steps to reproduce

1. Create new project with briefcase new iOS
2. Run cd helloworld
3. Run briefcase create iOS
4. Run briefcase build -u -r
5. Run briefcase open iOS
6. Within Xcode select my apple ID as team
7. Select my phone as destination in Xcode
8. Click the play button
9. See error

### Expected behavior

That my ios runs the same as in the simulation environment

### Environment

- Operating System: Mac OS
- Python version: Tried 3.10 and 3.12
- Software versions:
  - Briefcase: 0.3.20

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. It appears that the iOS template has inadvertently been hard-coded to Python 3.13.

I've pushed [a PR that will address the problem](https://github.com/beeware/briefcase-iOS-Xcode-template/pull/41); in the meantime, you can:

1. Add `template_branch = 'bad-py-version'` to your `pyproject.toml`, then re-run `briefcase create`. This will use the PR branch to generate your project; or
2. Manually modify your existing project. Select the root of the project tree, then Build Phases, then examine the script for "Sign Python Binary Modules"; line 39 and 40 each contain 1 reference to `python3.13`; replace this with 3.10/12 as appropriate, then do a clean build of your project
3. Switch to Python3.13 and re-create your project.

Apologies for the inconvienience, and thanks again for reporting the problem.

**Comment by kloknibor** [comment]
When I switched to Python3.13, I was still experiencing issues; however, when I used the bad-py-version, it worked as expected again! Thanks a lot for the quick help; the issue was driving me crazy. Should I close this issue or wait until the PR is merged?

**Comment by mhsmith** [comment]
Let's leave it open for visibility until it's been fixed for everyone.
